### ISSUE TITLE
Automatic Disk resize not working

### ISSUE THREAD

**Issue by dniasoff** [cloudbase/cloudbase-init#100]
Hi,

I have just prepared an image for server 2016 and whilst all went well, the disk wasn't automatically resized.

[cloudbase-init.zip](https://github.com/cloudbase/cloudbase-init/files/670319/cloudbase-init.zip)

I couldn't notice any issues in the log,

I can give you access to a VM with this issue if you'd like?

Thanks

Daniel

**Comment by ader1990** [comment]
This issue has been solved: https://bugs.launchpad.net/cloudbase-init/+bug/1520724
The fix is available on the cotinuous build cloudbase-init installer, downloadable from https://cloudbase.it/cloudbase-init/#download 

Please use launchpad for future bug reports, as we do not use this repo anymore.

Thank you,
Adrian Vladu
