### ISSUE TITLE
windows 2012 config ip failed

### ISSUE THREAD

**Issue by wywself** [cloudbase/cloudbase-init#44]
Hi Team,

When I use cloudbase-init to initialize the Windows 2012 IP address, it always shows that the device is not ready, and the log shows that the name of the network card failed to be modified, but when I entered the system and manually executed the command, it was successful.

can someone help me？

Regards
yuwei

![image](https://user-images.githubusercontent.com/8843053/79758237-b7f28200-834f-11ea-8e9a-fc17d89e1b27.png)

**Comment by ader1990** [comment]
Hello,

This kind of issue is usually the result of a laggy system, when the Windows services like wmi are not yet started at the time when Cloudbase-Init runs, due to low RAM or laggy CPU / disks. I suggest to set Cloudbase-Init service to Automatic (Delayed Start).

To reproduce the issue, can you give more information on the KVM version that you used, the CPU / RAM for the VM?

A possible fix for this problem (besides setting the service to delayed start), would be to have retries in place for every stage, but this can incur additional delays or issues in how Cloudbase-Init works.
Thank you,
Adrian Vladu

**Comment by wywself** [comment]
Thank you very much. I set`allow_reboot=true` and after reboot, ip configuration is successfully. I want to add some logs in cloudbase-init to get more error message. Is there any guide for compiling cloudbase-init msi? 

Regards
yuwei

**Comment by ader1990** [comment]
Here is the installer code: https://github.com/cloudbase/cloudbase-init-installer

If you fork my installer code, https://github.com/ader1990/cloudbase-init-installer-1/tree/nocloud_v2_net_support, you can use github actions to automatically build the installer.

Make sure you set the correct remote / branch for your case here: https://github.com/ader1990/cloudbase-init-installer-1/blob/nocloud_v2_net_support/.github/workflows/build_cbsinit.yml
