### ISSUE TITLE
Windows 2016 server is not booting

### ISSUE THREAD

**Issue by dmitrysmir5** [cloudbase/cloudbase-init#99]
After installing cloudbase-init 0.9.11-dev1 on Windows 2016 Server and creating a generalized OpenStack image from it, the instance itself starts well, but Windows boot up process cannot proceed till the login screen. Windows showing endless rotating circle and cmd popup windows with logdir, logfile, verbose deprecation warnings (same screen was seen on Windows 2012R2, but has no influence on booting ability).
Tried both on KVM (with VirtIO injection) and Hyper-V platforms.

![cloud-init-booting](https://cloud.githubusercontent.com/assets/23167795/19853732/bb947e36-9f73-11e6-8b7b-b5bc6b087df3.jpg)

**Comment by ader1990** [comment]
Hello,

can you try to share the cloudbase-init logs from the instance storage? by default they are located on the root partition, C:\Program Files\Cloudbase Solutions\Cloudbase-Init\log. As Windows failed to install, you can reach them only by accessing the underlying instance storage.

We added this behavior so that if Cloudbase-Init exits with a non zero code, the sysprep synchronouscommand will exit with a reboot-retry code, thus the behavior you are getting. For debugging purposes, you can remove the "&amp;&amp; exit 1 || exit 2" part from the runsynchronouscommand, found in the C:\Windows\Panther\unattend.xml and try to boot the new image with this change. If you perform the change, if cloudbase-init fails, the Windows boot process will not be affected.

Thank you.

**Comment by dmitrysmir5** [comment]
C:\Program Files\Cloudbase Solutions\Cloudbase-Init\log directory was empty when mapped disk to another working Windows host.

Removing "&amp;&amp exit 1 || exit 2" did solve Windows system booting issue, but cloudbase-init integration is not functioning fully. After such a boot, no network connectivity was available, btw. After removing VirtIO network adapter (version 0.1.126 is used) and re-scanning devices via Windows Device Manager the network adapter started working again. Log files after that boot are attached.

[cloudbase-init.log.txt](https://github.com/cloudbase/cloudbase-init/files/562156/cloudbase-init.log.txt)
[cloudbase-init-unattend.log.txt](https://github.com/cloudbase/cloudbase-init/files/562157/cloudbase-init-unattend.log.txt)

**Comment by ader1990** [comment]
Hello,

you can give it a try with the previous stable ones: https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.102/ . When the drivers work, is cloudbase-init able to access the metadata? You can just issue from powershell or cmd "net start cloudbase-init". Thanks.

**Comment by ader1990** [comment]
On the other hand, this is not a cloudbase-init issue, but a cloudbase-init installer issue or a drivers problem. I think it is better to open a bug on launchpad, as we don't use this repo anymore to track issues: https://launchpad.net/cloudbase-init

**Comment by dmitrysmir5** [comment]
VirtIO drivers are not guilty. On Win2016 network stack is not fully purged after cloudbase-init and sysprep execution. What is why OpenStack services cannot initiate and receive all required metadata.

![win2016_ncb_issue](https://cloud.githubusercontent.com/assets/23167795/19897838/6156894c-a062-11e6-9ff2-1f492e1442b1.JPG)

As a workaround "ipconfig /release" command was performed before installing cloudbase-init on the template machine.

**Comment by ader1990** [comment]
I understand. We are doing the same thing in the cloudbase windows image generation tool: https://github.com/cloudbase/windows-openstack-imaging-tools/blob/master/UnattendResources/Logon.ps1#L70

**Comment by ader1990** [comment]
Please close the issue, if the problem has been solved. I suggest for the future to try the imaging tools, as they are tested with all the supported Windows versions. Thanks.

**Comment by dmitrysmir5** [comment]
Thanks a lot.

**Comment by barrowkwan** [comment]
Hi, I am having similar issue but I am not use the imaging tool from cloudbase.  The reason is we have KVM all under Linux and we don't have hypervisor or windows host ( only have Windows VM ) to build the Windows image.  We also have automation tools to build our Openstack image ( windows and linux ).  I want to ask what exactly the cleanup task we need to do before install Cloud-init ?  I saw ipconfig release, is there any MUST clean up task.  thanks!

**Comment by ader1990** [comment]
Hello @barrowkwan ,

You can use the windows imaging tools, version 1.0.0, which can be used also only with a KVM hypervisor:
https://github.com/cloudbase/windows-openstack-imaging-tools/tree/v1.0.0

Thanks,
Adrian Vladu
